[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect /admin to TinaCMS admin
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Handle client-side routing for the admin panel
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle form submissions (contact form)
[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

# Default fallback for any other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300" 