[build]
  command = "npm install && npm run build"
  publish = "."
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables configured in Netlify dashboard:
# GITHUB_TOKEN = your_github_personal_access_token
# GITHUB_OWNER = SamPrestoo  
# GITHUB_REPO = iamlookingforvintage
# GITHUB_BRANCH = main
# STRIPE_SECRET_KEY = sk_test_... (or sk_live_... for production)
# STRIPE_PUBLISHABLE_KEY = pk_test_... (or pk_live_... for production)
# ADMIN_USERNAME = [your_admin_username]
# ADMIN_PASSWORD = [your_secure_password]

# Redirect /admin to admin login page
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Handle form submissions (contact form)
[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

# Allow specific HTML pages to load correctly
[[redirects]]
  from = "/admin-dashboard.html"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/shop.html"
  to = "/shop.html"
  status = 200

[[redirects]]
  from = "/about.html"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/cart.html"
  to = "/cart.html"
  status = 200

[[redirects]]
  from = "/product.html"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/success.html"
  to = "/success.html"
  status = 200

# Default fallback for any other routes (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers for better performance
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300" 